wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1715669990.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.8.18
      5: 0.16.4
      8:
      - 2
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 176
betas:
  desc: null
  value: 0.999)
eps:
  desc: null
  value: 1.0e-08
lr:
  desc: null
  value: 0.005
num_epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0
